services:
  bot:
    image: src
    container_name: src
    env_file:
      - ./src/.env
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./dbase/.env
    ports:
      - 5432:5432

volumes:
  postgres: