services:
  bot:
    image: bot
    container_name: bot
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0.12
    container_name: mongodb
    volumes:
      - dbase:/data/bot_db
    env_file:
      - ./dbase/.env
    ports:
      - 27017:27017

volumes:
  mongodb:
